# Generated by Django 5.1.3 on 2024-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareDevelopers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
