# Generated by Django 5.1.3 on 2024-12-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0004_softwaredevelopers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftwareDevelopers',
            new_name='SoftwareDeveloper',
        ),
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
    ]
